# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

fib_sequence = [1,2]
even_fib_sequence = []

for sum_last_two in fib_sequence:
	last_two = fib_sequence[-2:]
	sum_last_two = sum(last_two)
	if sum_last_two < 4000000:
		fib_sequence.append(sum_last_two)

for num in fib_sequence:
	if num % 2 == 0:
		even_fib_sequence.append(num)

sum_even_fib = sum(even_fib_sequence)
print sum_even_fib
